apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "nfs"
  claimRef:
    name: pv-claim
    namespace: default
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:                 
    name: pv-claim
    namespace: nginx
  nfs:
    path: /data/nfs-storage
    server: 127.0.0.1
