apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: nginx 
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

