apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy
  name: nginx-service
  namespace: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-deploy
  type: NodePort
status:
  loadBalancer: {}
